#5: Implement basic reddit auth using passport.js
rTeenDeveloper/hub pull request #23
Opened 2017-07-06 15:26 UTC by xrisk

Functions for:

1. Validating the reddit user against the DB
2. Serializing the user object into the session
3. Handling new user signup from reddit

have not been implemented yet and have been marked with TODO.

2017-07-06 19:52 UTC, asn007 requested changes
Fix my comments and we're good I think
P. S. Maybe erase session.state on callback too

2017-07-06 19:52 UTC, asn007 commented on packages/backend/package.json
> -    "dev:server": "nodemon src/index.js --exec babel-node",
Any reason for removal?

2017-07-06 19:52 UTC, asn007 commented on packages/backend/src/server.js
> +    app.get('/auth_status', (req, res) =>
We have API for it :p

2017-07-06 19:53 UTC, xrisk commented on packages/backend/src/server.js
> +    app.get('/auth_status', (req, res) =>
Oh I wrote this as kind of a utility endpoint...

2017-07-06 19:55 UTC, asn007 commented on packages/backend/src/server.js
> +    app.get('/auth_status', (req, res) =>
Move it into api/auth and it's good

2017-07-06 20:42 UTC, asn007 requested changes

2017-07-06 20:42 UTC, asn007 commented on packages/backend/src/api/1/handlers/auth.js
> +  if (req.query.state === req.session.state)
Actually from what I see, you can extract it into a middleware chain for that request and the code will get a little more readable imo

2017-07-06 20:42 UTC, asn007 commented on packages/backend/src/api/1/handlers/auth.js
> +router.get('/auth_status', (req, res) =>
Maybe just /status?

2017-07-06 20:42 UTC, asn007 commented on packages/backend/src/api/1/handlers/auth.js
> +    auth_status: req.isAuthenticated(),
You can actually just check if user is null / not null, so I doubt auth_status field is really needed

2017-07-06 20:42 UTC, asn007 commented on packages/backend/src/helpers/setupPassportStrategies.js
> +        clientID: 'rWjd7fOjL7eq3w',
Are these id / secret host bound? 
If so, we can actually keep it as part of our devenv

2017-07-06 20:42 UTC, asn007 commented on packages/backend/src/server.js
> +    app.get('/login_failure', (req, res) => {
Can be moved to API as well I think

2017-07-07 00:43 UTC, xrisk commented on packages/backend/src/helpers/setupPassportStrategies.js
> +        clientID: 'rWjd7fOjL7eq3w',
They are bound to my reddit account and the callback has to be specified in Reddit, but Reddit allows modifying the callback URL.

2017-07-07 11:54 UTC, asn007 approved these changes

2017-07-07 11:54 UTC, asn007 commented on packages/backend/src/api/1/handlers/auth.js
> +router.get(
Ain't really what I was asking.
I'll explain in PR comments more concise, but:
separate the endpoints so they're
/reddit
and
/reddit/callback

2017-07-07 11:54 UTC, asn007 requested changes
Will explain what I mean in comments to PR

2017-07-07 12:00 UTC, asn007 commented
You could actually abstract away that if() { passport(req, res, next) } ugly chain by utilising middleware in the following way:
```js
router.get('/reddit/callback', (req, res, next) => next(req.session.state !== req.query.state ? new Error(403) : undefined), passport.authenticate('reddit', { someData }))
```

2017-07-07 18:20 UTC, closed without merging

2017-07-10 16:22 UTC, asn007 commented
Approved